# Generated by Django 5.1 on 2025-11-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_order_products_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
