# Generated by Django 5.1 on 2025-11-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
